apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front-app
  template:
    metadata:
      labels:
        app: front-app
    spec:
      containers:
        - name: ai-react
          image: twentyfouritaiwan/ldap_frontend:0.2
          ports:
            - containerPort: 3000

