apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: front-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30090  # Optional: Specify a port in the range 30000-32767. If not provided, Kubernetes will assign one.
  type: NodePort
