# frontend-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  selector:
    app: front-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort

