kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-backend-sqlite
  namespace: kubeflow
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi

