apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: kubeflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: twentyfouritaiwan/ldap_backend:0.38
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /code/db
              name: sqlite-data
            - name: kubectl-binary
              mountPath: /usr/bin/kubectl
              readOnly: true
      #terminationMessagePath: /dev/termination-log
      #terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      serviceAccountName: jupyter-web-app-service-account
      volumes:
        - name: sqlite-data
          persistentVolumeClaim:
            claimName: pvc-backend-sqlite
        - name: kubectl-binary
          hostPath:
            path: /usr/bin/kubectl
            
