apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django-app  # This should match the labels of your Deployment
  ports:
    - protocol: TCP
      port: 80  # The port you want to expose externally
      targetPort: 8000  # The port your Django application is running on within the container
  type: NodePort  # You can use 'ClusterIP' or 'NodePort' based on your cluster's setup

