apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-container
          image: lms025187/backend  # Replace with your Django image and tag
          ports:
            - containerPort: 8000  # Adjust as needed
          volumeMounts:
            - name: db-storage
              mountPath: /code/db/  # Adjust the path as needed
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc  # Use the name of your PVC here

